Use industrial ci
mojin-robotics/flexbe_app pull request #15
Opened 2021-06-29 07:19 UTC by LoyVanBeek

2021-06-29 19:20 UTC, fmessmer requested changes
- did you include all changes I already proposed in https://github.com/FlexBE/flexbe_app/pull/60?
- I guess we should remove the `.github/workflows/flexbe_ci.yml` and only use the `main.yml` with the inducstrial_ci configs

2021-06-29 19:54 UTC, fmessmer commented
we are going to switch to industrial_ci in 
- https://github.com/mojin-robotics/generic_flexbe_states/pull/3
- https://github.com/mojin-robotics/flexbe_app/pull/15
- https://github.com/mojin-robotics/flexbe_behavior_engine/pull/14

thus the PRs related to (updated) flexbe_ci are no longer needed:
- https://github.com/mojin-robotics/flexbe_ci/pull/2
- https://github.com/mojin-robotics/generic_flexbe_states/pull/2
- https://github.com/mojin-robotics/flexbe_app/pull/14
- https://github.com/mojin-robotics/flexbe_behavior_engine/pull/13

2021-06-30 08:12 UTC, LoyVanBeek commented
Yes, the fixes suggested in https://github.com/FlexBE/flexbe_app/pull/60 are taken into account. The flexbe.desktop` file itself is made non-executable but the `bin/shortcut` installer of it makes it's copy executable.

2021-06-30 17:23 UTC, fmessmer approved these changes

2021-06-30 17:23 UTC, merged